### ISSUE TITLE
Release the source code

### ISSUE THREAD

**Issue by cccchensir** [eugenelyj/eugenelyj.github.io#1]
Dear author,

      Thank you for ur insightful work: Graph-based Asynchronous Event Processing for Rapid Object Recognition. I am wonder how to acess the source code corresponding to this amazing paper?

**Comment by eugenelyj** [comment]
Thanks for your interest in our work. Currently, I do not have a plan to release the code. But you can refer to [AEGNN](https://github.com/uzh-rpg/aegnn) as it almost shares the main idea with ours but extends it somehow.
